const SUPABASE_URL='https://mosexjnulqhlulnliazv.supabase.co';
const SUPABASE_KEY='sb_publishable_eoxClJS-KpkzHZMudL_eBQ_IGrlLbj-';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let currentId=null, records=[];
const $=s=>document.querySelector(s);
const els={serial:$('#serial'),inspectionDate:$('#inspectionDate'),nextDate:$('#nextDate'),customer:$('#customerSelect'),inspectionType:$('#inspectionTypeSelect'),result:$('#resultSelect'),summary:$('#summary'),itemsBody:$('#itemsTable tbody'),defectsBody:$('#defectsTable tbody'),status:$('#status'),records:$('#recordsList'),search:$('#search')};

function setStatus(msg,type='ok'){els.status.textContent=msg;els.status.className='status '+type}
function rowInput(value='',type='text'){return `<input type="${type}" value="${String(value??'').replaceAll('"','&quot;')}">`}
function addItem(item={}){const tr=document.createElement('tr');tr.innerHTML=`<td class="num"></td><td>${rowInput(item.description)}</td><td>${rowInput(item.manufacturer)}</td><td>${rowInput(item.serial_number)}</td><td>${rowInput(item.load)}</td><td>${rowInput(item.angle)}</td><td>${rowInput(item.price)}</td><td><button class="remove" type="button">×</button></td>`;tr.querySelector('.remove').onclick=()=>{tr.remove();renumber(els.itemsBody)};els.itemsBody.append(tr);renumber(els.itemsBody)}
function addDefect(item={}){const tr=document.createElement('tr');tr.innerHTML=`<td class="num"></td><td>${rowInput(item.description)}</td><td>${rowInput(item.internal_number)}</td><td>${rowInput(item.due_date,'date')}</td><td><button class="remove" type="button">×</button></td>`;tr.querySelector('.remove').onclick=()=>{tr.remove();renumber(els.defectsBody)};els.defectsBody.append(tr);renumber(els.defectsBody)}
function renumber(body){[...body.rows].forEach((r,i)=>r.querySelector('.num').textContent=i+1)}
function tableData(body,fields){return [...body.rows].map(r=>{const vals=[...r.querySelectorAll('input')].map(i=>i.value.trim());return Object.fromEntries(fields.map((f,i)=>[f,vals[i]||'']))}).filter(o=>Object.values(o).some(Boolean))}

async function loadDictionary(kind,select){const {data,error}=await db.from('dictionary_items').select('*').eq('kind',kind).eq('active',true).order('label');if(error){setStatus('יש להריץ את קובץ supabase-schema.sql ב-Supabase','error');return}select.innerHTML='<option value="">בחר...</option>'+data.map(x=>`<option value="${x.label}">${x.label}</option>`).join('')}
async function addDictionary(kind){const label=prompt('הכנס פריט חדש');if(!label)return;const {error}=await db.from('dictionary_items').insert({kind,label:label.trim()});if(error)return setStatus(error.message,'error');await loadAllDictionaries();setStatus('הפריט נוסף למאגר')}
async function loadAllDictionaries(){await Promise.all([loadDictionary('customers',els.customer),loadDictionary('inspection_types',els.inspectionType),loadDictionary('results',els.result)])}

function getForm(){return{serial_number:els.serial.value.trim(),inspection_date:els.inspectionDate.value||null,next_inspection_date:els.nextDate.value||null,customer:els.customer.value,inspection_type:els.inspectionType.value,result:els.result.value,summary:els.summary.value.trim(),items:tableData(els.itemsBody,['description','manufacturer','serial_number','load','angle','price']),defects:tableData(els.defectsBody,['description','internal_number','due_date']),updated_at:new Date().toISOString()}}
async function save(){const payload=getForm();if(!payload.serial_number)return setStatus('חובה להזין מספר סידורי','error');let q=currentId?db.from('memos').update(payload).eq('id',currentId):db.from('memos').insert(payload).select().single();const {data,error}=await q;if(error)return setStatus(error.message,'error');if(data?.id)currentId=data.id;setStatus('התסקיר נשמר בענן');await loadRecords()}
async function loadRecords(){const {data,error}=await db.from('memos').select('*').order('created_at',{ascending:false});if(error)return setStatus('החיבור למסד עדיין לא הושלם','error');records=data||[];renderRecords();const requestedId=Number(new URLSearchParams(location.search).get('id'));if(requestedId){const found=records.find(r=>r.id===requestedId);if(found)fillForm(found)}}
function renderRecords(){const q=els.search.value.trim().toLowerCase();els.records.innerHTML='';records.filter(r=>[r.serial_number,r.customer,r.summary].join(' ').toLowerCase().includes(q)).slice(0,20).forEach(r=>{const d=document.createElement('div');d.className='record';d.innerHTML=`<strong>${r.serial_number||'ללא מספר'}</strong><small>${r.customer||''} · ${r.inspection_date||''}</small>`;d.onclick=()=>fillForm(r);els.records.append(d)})}
function fillForm(r){currentId=r.id;els.serial.value=r.serial_number||'';els.inspectionDate.value=r.inspection_date||'';els.nextDate.value=r.next_inspection_date||'';setSelect(els.customer,r.customer);setSelect(els.inspectionType,r.inspection_type);setSelect(els.result,r.result);els.summary.value=r.summary||'';els.itemsBody.innerHTML='';(r.items||[]).forEach(addItem);if(!r.items?.length)addItem();els.defectsBody.innerHTML='';(r.defects||[]).forEach(addDefect);if(!r.defects?.length)addDefect();scrollTo({top:0,behavior:'smooth'});setStatus('התסקיר נטען לעריכה')}
function setSelect(sel,val){if(val&&![...sel.options].some(o=>o.value===val))sel.add(new Option(val,val));sel.value=val||''}
function reset(){currentId=null;history.replaceState({},'',location.pathname);document.querySelectorAll('input,textarea').forEach(i=>{if(i.id!=='search')i.value=''});document.querySelectorAll('select').forEach(s=>s.value='');els.itemsBody.innerHTML='';els.defectsBody.innerHTML='';addItem();addDefect();els.inspectionDate.value=new Date().toISOString().slice(0,10);setStatus('תסקיר חדש')}

function preparePrint(){const f=getForm();$('#pSerial').textContent=f.serial_number;$('#pInspectionDate').textContent=f.inspection_date||'';$('#pNextDate').textContent=f.next_inspection_date||'';$('#pCustomer').textContent=f.customer||'';$('#pInspectionType').textContent=f.inspection_type||'';$('#pResult').textContent=f.result||'';$('#pSummary').textContent=f.summary||'';$('#pItems tbody').innerHTML=f.items.map((x,i)=>`<tr><td>${i+1}</td><td>${x.description}</td><td>${x.manufacturer}</td><td>${x.serial_number}</td><td>${x.load}</td><td>${x.angle}</td><td>${x.price}</td></tr>`).join('');$('#pDefects tbody').innerHTML=f.defects.map((x,i)=>`<tr><td>${i+1}</td><td>${x.description}</td><td>${x.internal_number}</td><td>${x.due_date}</td></tr>`).join('');window.print()}

document.querySelectorAll('[data-dict]').forEach(b=>b.onclick=()=>addDictionary(b.dataset.dict));$('#addItemBtn').onclick=()=>addItem();$('#addDefectBtn').onclick=()=>addDefect();$('#saveBtn').onclick=save;$('#printBtn').onclick=preparePrint;$('#newBtn').onclick=reset;els.search.oninput=renderRecords;
(async()=>{reset();await loadAllDictionaries();await loadRecords()})();