const SUPABASE_URL='https://mosexjnulqhlulnliazv.supabase.co';
const SUPABASE_KEY='sb_publishable_eoxClJS-KpkzHZMudL_eBQ_IGrlLbj-';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s);
let types=[],items=[];
const els={id:$('#equipmentId'),name:$('#equipmentName'),type:$('#equipmentType'),serial:$('#equipmentSerial'),manufacturer:$('#equipmentManufacturer'),model:$('#equipmentModel'),catalog:$('#equipmentCatalog'),load:$('#equipmentLoad'),unit:$('#equipmentUnit'),branches:$('#equipmentBranches'),c30:$('#capacity30'),c45:$('#capacity45'),c60:$('#capacity60'),notes:$('#equipmentNotes'),angles:$('#angleFields'),search:$('#equipmentSearch'),list:$('#equipmentList'),status:$('#equipmentStatus'),title:$('#equipmentFormTitle')};
function setStatus(message,type='ok'){els.status.textContent=message;els.status.className='status '+type}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function numberOrNull(input){return input.value===''?null:Number(input.value)}
async function loadTypes(){const {data,error}=await db.from('equipment_types').select('*').eq('active',true).order('name');if(error){setStatus('יש להריץ את supabase-migration-v2.sql ב-Supabase','error');return}types=data||[];els.type.innerHTML='<option value="">בחר סוג...</option>'+types.map(t=>`<option value="${t.id}">${escapeHtml(t.name)}</option>`).join('');toggleAngles()}
async function loadItems(){const {data,error}=await db.from('equipment_items').select('*,equipment_types(name,angle_capacity_enabled)').eq('active',true).order('name');if(error){setStatus('לא ניתן לטעון את מאגר הפריטים','error');return}items=data||[];renderItems()}
function toggleAngles(){const selected=types.find(t=>String(t.id)===els.type.value);els.angles.hidden=!selected?.angle_capacity_enabled}
function renderItems(){const q=els.search.value.trim().toLowerCase();els.list.innerHTML='';items.filter(i=>[i.name,i.serial_number,i.manufacturer,i.model,i.catalog_number,i.equipment_types?.name].join(' ').toLowerCase().includes(q)).forEach(i=>{const card=document.createElement('div');card.className='record';card.innerHTML=`<strong>${escapeHtml(i.name)}</strong><small>${escapeHtml(i.equipment_types?.name||'')} ${i.serial_number?'· '+escapeHtml(i.serial_number):''}</small>`;card.onclick=()=>openItem(i);els.list.append(card)});if(!els.list.children.length)els.list.innerHTML='<div class="empty-state">לא נמצאו פריטים. אפשר ליצור פריט חדש.</div>'}
function openItem(i){els.id.value=i.id;els.name.value=i.name||'';els.type.value=i.equipment_type_id||'';els.serial.value=i.serial_number||'';els.manufacturer.value=i.manufacturer||'';els.model.value=i.model||'';els.catalog.value=i.catalog_number||'';els.load.value=i.working_load??'';els.unit.value=i.load_unit||'kg';els.branches.value=i.branches_count??'';els.c30.value=i.capacity_30??'';els.c45.value=i.capacity_45??'';els.c60.value=i.capacity_60??'';els.notes.value=i.notes||'';els.title.textContent='עריכת פריט';toggleAngles();scrollTo({top:0,behavior:'smooth'})}
function payload(){return{equipment_type_id:els.type.value?Number(els.type.value):null,name:els.name.value.trim(),serial_number:els.serial.value.trim()||null,manufacturer:els.manufacturer.value.trim(),model:els.model.value.trim(),catalog_number:els.catalog.value.trim(),working_load:numberOrNull(els.load),load_unit:els.unit.value,branches_count:numberOrNull(els.branches),capacity_30:numberOrNull(els.c30),capacity_45:numberOrNull(els.c45),capacity_60:numberOrNull(els.c60),notes:els.notes.value.trim(),updated_at:new Date().toISOString()}}
async function saveItem(){const data=payload();if(!data.name)return setStatus('חובה להזין שם פריט','error');const selected=types.find(t=>t.id===data.equipment_type_id);if(selected?.requires_serial&&!data.serial_number)return setStatus('לסוג פריט זה נדרש מספר סידורי','error');const id=Number(els.id.value);const query=id?db.from('equipment_items').update(data).eq('id',id).select().single():db.from('equipment_items').insert(data).select().single();const {data:saved,error}=await query;if(error)return setStatus(error.code==='23505'?'המספר הסידורי כבר קיים במערכת':error.message,'error');setStatus('הפריט נשמר');await loadItems();if(saved)openItem({...saved,equipment_types:types.find(t=>t.id===saved.equipment_type_id)})}
function resetForm(){els.id.value='';[els.name,els.serial,els.manufacturer,els.model,els.catalog,els.load,els.branches,els.c30,els.c45,els.c60,els.notes].forEach(x=>x.value='');els.type.value='';els.unit.value='kg';els.title.textContent='פריט חדש';toggleAngles();setStatus('')}
els.type.onchange=toggleAngles;els.search.oninput=renderItems;$('#saveEquipmentBtn').onclick=saveItem;$('#newEquipmentBtn').onclick=resetForm;
(async()=>{await loadTypes();await loadItems()})();
